config/routes.rb
Rails.application.routes.draw do

  get 'home', to: 'home#index'
  root to: 'home#index'

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'authentication#new'
  post 'sign_in', to: 'authentication#create'
  delete 'logout', to: 'authentication#destroy'

  get 'new_transaction/:type', to: 'transactions#new'
  post 'create_transaction', to: 'transactions#create'


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :transactions, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :user

end

app/models/new_user_offer.rb
# frozen_string_literal: true

class NewUserOffer < ApplicationRecord
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  belongs_to :to_account, :class_name => 'User', foreign_key: 'to_account_id', required: false
  belongs_to :from_account, :class_name => 'User', foreign_key: 'from_account_id', required: false

  TRANSACTION_TYPES = %w[withdrawal deposit transfer]

  validates :transaction_type, inclusion: { in: TRANSACTION_TYPES }
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username , presence: true, uniqueness: true

  has_many :incoming_transactions, :class_name => 'Transaction', :foreign_key => 'to_account_id'
  has_many :outgoing_transactions, :class_name => 'Transaction', :foreign_key => 'from_account_id'

  def transactions
    self.outgoing_transactions.or(self.incoming_transactions)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end
end

app/controllers/authentication_controller.rb
# frozen_string_literal: true

class AuthenticationController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to sign_in_path, alert: 'Login failed. Please Retry'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to sign_in_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @new_user = User.new
  end

  def create
    @new_user = User.new(user_params)

    add_intro_offers

    if @new_user.save
      session[:user_id] = @new_user.id
      redirect_to root_path
    else
      redirect_to sign_up_path, alert:'Something went wrong'
    end
  end

  private

  def add_intro_offers
    NewUserOffer.all.each do |offer|
      @new_user.balance += offer.amount
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :validate_user, only: [:create]


  def index
    @transactions = Current.user.transactions.order(created_at: :desc)
  end

  def new
    redirect_to '/transactions' unless %w[deposit withdrawal transfer].include? params[:type]
    @transaction = Transaction.new(transaction_type: params[:type])
  end

  def create
    Transaction.transaction do
      case transaction_params[:transaction_type]
      when 'deposit'
        @transaction = Current.user.incoming_transactions.new(transaction_params)
        @transaction_amount = @transaction.amount
      when 'transfer', 'withdrawal'
        @transaction = Current.user.outgoing_transactions.new(transaction_params)
        @transaction_amount = -@transaction.amount
        if transaction_params[:transaction_type] == 'transfer'
          @recipient = User.find_by!(username: params[:recipient])
          @transaction.to_account = @recipient
        end
      else
        raise "Incorrect Type"
      end

      update_balances
      @transaction.save!
      redirect_to '/transactions'
    end
  rescue => error
    ::Rails.logger.info error
    redirect_to '/transactions'
  end


  private

  def update_balances
    Current.user.update!(balance: Current.user.balance + @transaction_amount)
    @recipient.update!(balance: @recipient.reload.balance + (-@transaction_amount)) if @recipient
  end

  def transaction_params
    params.require(:transaction).permit(:amount, :transaction_type)
  end

  def validate_user
    raise Error 'Invalid user' if params[:username] != Current.user.username
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
<h1>Sign In </h1>

<div classname="flash-messages">
  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>
</div>

<%= form_with url: sign_in_path do |f| %>

<%= f.label :Username %>
<%= f.text_field :username %>

<%= f.label :Password %>
<%= f.password_field :password %>

<%= f.submit "Sign in" %>
<% end %>

app/views/home/index.html.erb
<h2>Home Page</h2>

<% if Current.user %>
  <div>
    Balance: <%= Current.user.balance %> Silveuros
  </div>
  <br>

  <%= button_to "Sign Out", logout_path,  method: :delete %>
<% else %>
  <%= link_to "Sign up", sign_up_path %>
  <%= link_to "Sign In", sign_in_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BankingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <% if Current.user %>
     <%= render partial: 'navigation/navbar' %>
    <% end %>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/navigation/_navbar.html.erb
<div class="navbar">
  <div>Navbar</div>
  <a href="/home">Home</a>
  <a href="/transactions">Transactions</a>
  <div class="username"><%= Current.user.username %></div>
</div>

app/views/transactions/index.html.erb
<h2>Transactions</h2>
<a href="new_transaction/withdrawal">Withdraw</a>
<a href="new_transaction/deposit">Deposit</a>
<a href="new_transaction/transfer">Transfer</a>
<div class="transactions-table">
  <table>
    <tr>
      <td> Transaction Type </td>
      <td> Amount </td>
      <td> From Account </td>
      <td> Date </td>
    </tr>

    <% @transactions.each do |transaction| %>
      <tr class=<%= transaction.transaction_type %>>
        <td><%= transaction.transaction_type.capitalize %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.from_account&.username || '' %></td>
        <td><%= transaction.created_at %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/transactions/new.html.erb
<%= form_with model: @transaction, url: create_transaction_path do |f|  %>
  <%= @transaction.transaction_type&.capitalize %>

  <br>

  <%= f.label :Amount %>
  <%= f.number_field :amount %>

  <% if @transaction.transaction_type == 'transfer'%>
    <label for="recipient">Recipient</label>
    <input type="text" name="recipient" id="recipient">
  <% end%>

  <input autocomplete="off" type="hidden"
         value=<%=@transaction.transaction_type%> name="transaction[transaction_type]" id="transaction_type">
  <input autocomplete="off" type="hidden"
         value=<%=Current.user.username %> name="username" id=username">


  <%= f.submit "Process" %>
<% end %>